### PR TITLE
Tennis rating implement

### PR DESCRIPTION
**Pull request by xw19**
I tried to implement the rating system
Assumption:  The scores are of individual match
I have tried to keep it simple although it could be done in less amount of code.
When I import the data from yaml file I get array a string containg match results. Now breaking the string and converting it into a array where each array represents a match and a subarray represents a set. For each wining set that is if 0th element is greater than the 1st two points are given minus the ratio of lost/won. The result is added for each set.

### CODE REVIEW

**Comment by xw19** [comment]
Should I write this in form of a class ?

**Comment by cpg** [comment]
It's a good start, but I was expecting a significant amount more.

i think this should be in the form of a _method_, so we can tweak things.

however, that is the least of the issues here.
- the code does not use the tennis gem to analyze the score and do accounting based on the interface from the gem
- it's structured in a rather not-so-readable way. it took me a bit of reading through the code to know what was going on
- there is floating point arithmetic -- seems like an unnecessary thing to do
- ultimately, it does not seem like the beginning of a framework to tune/test rating systems (e.g. against each other)

I think the code does not seem stylistically very ruby-esque. Not a very very bad thing, but still, it reads off to a ruby person.

**Comment by xw19** [comment]
This is not appropriate

**Comment by xw19** [comment]
The rewrite in form of class and use of tennis gem also proper points resolution

**Pull request merged**
